from typing import Protocol

from domain.entities.passport_group_entity import PassportGroupEntity


class PassportGroupRepositoryProtocol(Protocol):
    async def get_by_id(self, _id: int) -> PassportGroupEntity | None: ...
    async def get_by_filters(self, filters: dict) -> PassportGroupEntity | None: ...
    async def get_by_name(self, name: str) -> PassportGroupEntity | None: ...
    async def add(self, entity: PassportGroupEntity) -> PassportGroupEntity: ...
    async def update(self, user_entity: PassportGroupEntity) -> PassportGroupEntity: ...
    async def delete(self, _id: int) -> None: ...
    async def get_many(
        self,
        skip: int = 0,
        limit: int | None = None,
        order_by: list | None = None,
        **filters,
    ) -> list[PassportGroupEntity]: ...
