from typing import Protocol

from domain.regions.region_entity import RegionEntity


class RegionsRepositoryProtocol(Protocol):
    async def get_by_id(self, _id: int) -> RegionEntity | None: ...
    async def get_by_filters(self, filters: dict) -> RegionEntity | None: ...
    async def get_by_code(self, code: int) -> RegionEntity | None: ...
    async def get_by_name(self, name: str) -> RegionEntity | None: ...
    async def add(self, entity: RegionEntity) -> RegionEntity: ...
    async def update(self, user_entity: RegionEntity) -> RegionEntity: ...
    async def delete(self, _id: int) -> RegionEntity: ...
    async def get_many(
        self,
        skip: int,
        limit: int | None,
        order_by: list | None,
        **filters,
    ) -> list[RegionEntity]: ...
