from typing import Protocol

from domain.traffic_light_objects.tlo_entity import TrafficLightObjectEntity


class TrafficLightObjectRepositoryProtocol(Protocol):
    # async def get_by_id(self, region_id: int) -> TrafficLightObjectEntity: ...
    async def try_by_id(self, region_id: int) -> TrafficLightObjectEntity | None: ...
    async def try_by_filters(self, filters: dict) -> TrafficLightObjectEntity | None: ...
    async def get_by_name(self, code_or_name: str) -> TrafficLightObjectEntity: ...
    async def get_many(
        self,
        skip: int,
        limit: int,
        order_by: list | None,
        **filters
    ) -> list[TrafficLightObjectEntity]: ...
    async def create(self, entity: TrafficLightObjectEntity) -> TrafficLightObjectEntity: ...
    async def update(self, user_entity: TrafficLightObjectEntity) -> TrafficLightObjectEntity: ...
    async def delete(self, _id: int) -> TrafficLightObjectEntity: ...

