from typing import Protocol
from domain.entities import UserEntity


class UsersRepositoryProtocol(Protocol):
    async def get_by_id(self, _id: int) -> UserEntity | None: ...
    async def get_by_username(self, username: str) -> UserEntity | None: ...
    async def add(self, entity: UserEntity) -> UserEntity: ...
    async def update(self, user_entity: UserEntity) -> None: ...
    async def delete(self, _id: int) -> None: ...
