from typing import Protocol

from domain.repositories.base_repo_interfaces import BaseCrudRepositoryProtocol
from domain.users.user_entity import UserEntity


class UsersReadRepositoryProtocol(
    BaseCrudRepositoryProtocol[UserEntity],
    Protocol
):
    async def get_by_username(self, username: str) -> UserEntity: ...
    async def try_by_username(self, username: str) -> UserEntity | None: ...
    # async def change_password(self, _id: int, hashed_password: bytes) -> None: ...


# class UsersRepositoryProtocol(Protocol):
#     async def get_by_id(self, _id: int) -> UserEntity | None: ...
#     async def get_user_by_filters(self, **filters) -> UserEntity | None: ...
#     async def get_by_username(self, username: str) -> UserEntity | None: ...
#     async def add(self, entity: UserEntity) -> UserEntity: ...
#     async def update(self, user_entity: UserEntity) -> None: ...
#     async def change_password(self, _id: int, hashed_password: bytes) -> None: ...
#     async def delete(self, _id: int) -> None: ...
