from typing import Protocol


class BaseCrudProtocol(Protocol):

    async def get_one_by_id_or_none(self, _id: int): ...

    async def get_one_or_none_by_filters(self, **filters): ...

    async def get_all(self): ...

    async def add(self, entity): ...

    # async def update(self, model): ...
    async def update(self, _id: int, **fields,): ...




