from typing import Protocol


class BaseCrudProtocol(Protocol):

    async def get_one_by_id(self, _id: int): ...

    async def get_all(self): ...

    async def add(self, entity): ...

    async def update(self, model): ...