"""create TrafficLightObject, Region, OvimPassport tables

Revision ID: 2c45c894f19f
Revises: 02220211904e
Create Date: 2025-11-10 10:35:45.447067

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c45c894f19f'
down_revision: Union[str, Sequence[str], None] = '02220211904e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'regions',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('code', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_regions')),
        sa.UniqueConstraint('name', name=op.f('uq_regions_name')),
    )
    op.create_table(
        'traffic_light_objects',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('region_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=32), nullable=False),
        sa.Column('district', sa.String(), server_default='', nullable=False),
        sa.Column('street', sa.Text(), nullable=False),
        sa.Column('description', sa.Text(), server_default='', nullable=False),
        sa.Column('ovim_in_use', sa.Boolean(), server_default='false', nullable=False),
        sa.Column(
            'construction_in_use', sa.Boolean(), server_default='false', nullable=False
        ),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column(
            'updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['region_id'],
            ['regions.id'],
            name=op.f('fk_traffic_light_objects_region_id_regions'),
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_traffic_light_objects')),
        sa.UniqueConstraint('name', name=op.f('uq_traffic_light_objects_name')),
        sa.UniqueConstraint(
            'region_id', name=op.f('uq_traffic_light_objects_region_id')
        ),
    )
    op.create_table(
        'ovim_passports',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('tlo_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('commit_message', sa.String(length=255), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ['tlo_id'],
            ['traffic_light_objects.id'],
            name=op.f('fk_ovim_passports_tlo_id_traffic_light_objects'),
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk_ovim_passports_user_id_users')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_ovim_passports')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ovim_passports')
    op.drop_table('traffic_light_objects')
    op.drop_table('regions')
    # ### end Alembic commands ###
