"""create Passports table

Revision ID: 1a90c7f3712d
Revises: aef9ff824d74
Create Date: 2025-11-16 13:40:01.614860

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1a90c7f3712d'
down_revision: Union[str, Sequence[str], None] = 'aef9ff824d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'passports',
        sa.Column('tlo_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=False),
        sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column('commit_message', sa.Text(), nullable=True),
        sa.Column('editing_now', sa.Boolean(), server_default='true', nullable=False),
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            'started_editing_at',
            sa.DateTime(),
            server_default=sa.text('now()'),
            nullable=False,
        ),
        sa.Column('finished_editing_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['group_id'],
            ['passport_groups.id'],
            name=op.f('fk_passports_group_id_passport_groups'),
        ),
        sa.ForeignKeyConstraint(
            ['tlo_id'],
            ['traffic_light_objects.id'],
            name=op.f('fk_passports_tlo_id_traffic_light_objects'),
        ),
        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'], name=op.f('fk_passports_user_id_users')
        ),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_passports')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('passports')
    # ### end Alembic commands ###
