from typing import Protocol, Any


class CacheFieldProtocol(Protocol):
    def add(self, value: Any): ...
    # def remove(self, key: Any) -> Any | None: ...
    def clear(self): ...
    def __contains__(self, value: Any) -> bool: ...
