users = [
    {
        'first_name': 'Test',
        'last_name': 'Testov',
        'username': 'test1',
        'organization': 'Spetsdorproject',
        'email': 'user@example.com',
        'password': b'1234',
        'is_active': True,
        'is_admin': True,
        'is_superuser': True,
        'role': 'superuser',
        'phone_number': '',
        'telegram': '',
        'description': 'Тестовый юзер 1',
    },
    {
        'first_name': 'Test1',
        'last_name': 'Testov1',
        'username': 'test2',
        'organization': 'Spetsdorproject',
        'email': 'user@example.com',
        'password': b'1234',
        'is_active': True,
        'is_admin': True,
        'is_superuser': True,
        'role': 'superuser',
        'phone_number': '',
        'telegram': '',
        'description': 'Тестовый юзер 2',
    },
    {
        'first_name': 'Test3',
        'last_name': 'Testov3',
        'username': 'test3',
        'organization': 'Spetsdorproject',
        'email': 'user@example.com',
        'password': b'1234',
        'is_active': True,
        'is_admin': True,
        'is_superuser': True,
        'role': 'superuser',
        'phone_number': '',
        'telegram': '',
        'description': 'Тестовый юзер 3',
    },
    {
        'first_name': 'Test4',
        'last_name': 'Testov4',
        'username': 'test4',
        'organization': 'Spetsdorproject',
        'email': '',
        'password': b'1234',
        'is_active': True,
        'is_admin': True,
        'is_superuser': True,
        'role': 'superuser',
        'phone_number': '',
        'telegram': '',
        'description': 'Тестовый юзер 4',
    },
]
