from typing import Protocol, Any

from domain.entities.region_entity import RegionEntity


class RegionsReadServiceProtocol(Protocol):
    async def get_region_by_filters(self, **filters) -> RegionEntity | None: ...
    async def get_region_by_id(self, id: int) -> RegionEntity | None: ...
    async def get_region_by_code(self, code: int) -> RegionEntity | None: ...
    async def get_region_by_name(self, username: str) -> RegionEntity | None: ...
    async def get_region_by_id_or_raise(self, _id: int) -> RegionEntity: ...
    async def get_many(
        self,
        skip: int,
        limit: int,
        order_by: list | None,
    ) -> list[RegionEntity]: ...

class RegionsWriteServiceProtocol(Protocol):
    async def update_region(self, user_id: int, update_data) -> RegionEntity: ...
    async def add_new_region(self, user_data: RegionEntity) -> RegionEntity: ...


class RegionsServiceProtocol(
    RegionsReadServiceProtocol, RegionsWriteServiceProtocol, Protocol
): ...
