from typing import Protocol, Sequence

from application.dtos.users import CreateUserDTO, UpdateUserDTO
from core.users.entities.user import UserEntity


class UsersServiceProtocol(Protocol):
    async def get_user_by_username_or_none(self, name: str) -> UserEntity: ...

    async def get_user_by_id_or_none(self, user_id: int) -> UserEntity: ...

    async def get_all_users(self) -> Sequence[UserEntity]: ...

    async def create_user(self, user: CreateUserDTO) -> UserEntity: ...

    async def update_user(self, user: UpdateUserDTO) -> UserEntity: ...

    async def change_password(self, user: UpdateUserDTO) -> UserEntity: ...
