from collections.abc import Container
from typing import Protocol

from application.use_cases.users.commands import ChangeUserPasswordCommand
from domain.kernel.enums.unsorted import Roles
from domain.users.user_entity import UserEntity


class UserReadServiceProtocol(Protocol):
    async def get_by_username(self, username: str) -> UserEntity: ...
    async def try_by_username(self, username: str) -> UserEntity | None: ...
    async def try_get_user_by_id(self, user_id: int) -> UserEntity | None: ...
    async def get_by_id(self, user_id: int) -> UserEntity: ...
    async def try_by_id(self, user_id: int) -> UserEntity | None: ...
    async def get_active_user_by_id(self, user_id: int) -> UserEntity: ...
    async def get_active_user_by_id_and_check_role(
        self, user_id: int, required_roles: Container[Roles], action: str
    ) -> UserEntity: ...

    async def verify_user_is_active(self, user_id: int, action: str) -> None: ...
    async def verify_user_is_active_and_has_roles(
        self,
        user_id: int,
        required_roles: Container[Roles],
        action: str,
    ) -> None: ...


class UserUpdateServiceProtocol(Protocol):
    async def change_password(self, command: ChangeUserPasswordCommand) -> UserEntity: ...


class UserServiceProtocol(
    UserReadServiceProtocol, UserUpdateServiceProtocol, Protocol
): ...


class AdminUserServiceProtocol(UserServiceProtocol, Protocol): ...