from collections.abc import Container
from typing import Protocol

from domain.kernel.enums.unsorted import Roles
from domain.users.user_entity import UserEntity


class UserReadServiceProtocol(Protocol):
    async def try_get_user_by_filters(self, **filters) -> UserEntity | None: ...
    async def try_get_user_by_username(self, username: str) -> UserEntity | None: ...
    async def try_get_user_by_id(self, user_id: int) -> UserEntity | None: ...

    async def get_user_by_id(self, user_id: int) -> UserEntity: ...
    async def get_active_user_by_id(self, user_id: int) -> UserEntity: ...
    async def get_active_user_by_id_and_check_role(
        self, user_id: int, required_roles: Container[Roles]
    ) -> UserEntity: ...

    async def verify_user_is_active(self, user_id: int) -> None: ...
    async def verify_user_is_active_and_has_roles(
        self,
        user_id: int,
        required_roles: Container[Roles],
        action: str,
    ) -> None: ...


class UserWriteServiceProtocol(Protocol):
    async def update_user(self, user_id: int, update_data) -> UserEntity: ...
    async def change_password(
        self, user_id: int, hashed_password: bytes
    ) -> UserEntity | None: ...
    async def add_new_user(self, user_data: UserEntity) -> UserEntity: ...


class UserServiceProtocol(
    UserReadServiceProtocol, UserWriteServiceProtocol, Protocol
): ...
