from typing import Protocol

from domain.entities import UserEntity


class UserReadServiceProtocol(Protocol):
    async def get_user_by_filters(self, **filters) -> UserEntity | None: ...
    async def get_user_by_username(self, username: str) -> UserEntity | None: ...
    async def get_user_by_id(self, id: int) -> UserEntity | None: ...
    async def get_user_by_id_or_raise(self, _id: int) -> UserEntity: ...
    async def get_active_user_by_id_or_raise(self, _id: int) -> UserEntity: ...


class UserWriteServiceProtocol(Protocol):
    async def update_user(self, user_id: int, update_data) -> UserEntity: ...
    async def change_password(
        self, user_id: int, hashed_password: bytes
    ) -> UserEntity | None: ...
    async def add_new_user(self, user_data: UserEntity) -> UserEntity: ...


class UserServiceProtocol(
    UserReadServiceProtocol, UserWriteServiceProtocol, Protocol
): ...
