from typing import Protocol


class PasswordServiceProtocol(Protocol):

    def hash_password(self, password: str) -> bytes: ...
    def verify_password(self, password: str, hashed_password: bytes) -> bool: ...
    def generate_password(self) -> str: ...
